from PyQt6.QtWidgets import (QDialog, QVBoxLayout, QFormLayout, QLineEdit,
                             QTextEdit, QComboBox, QDialogButtonBox, QLabel, QMessageBox) # Added QMessageBox
from PyQt6.QtCore import Qt

class AddLedgerEntryDialog(QDialog):
    def __init__(self, default_jurisdiction="Lex Aequies", parent=None):
        super().__init__(parent)
        self.setWindowTitle("Add New Ledger Entry")

        self.entry_data = {}

        main_layout = QVBoxLayout(self)
        form_layout = QFormLayout()

        self.title_edit = QLineEdit()
        self.title_edit.setPlaceholderText("Enter a concise title for the ledger entry.")
        form_layout.addRow(QLabel("Title:"), self.title_edit)

        self.entry_type_combo = QComboBox()
        self.entry_types = [
            "Transaction", "Notice Sent", "Notice Received", "Filing",
            "Clause Reference", "Amendment", "Trustee Action", "System Event", "User Note", "Other"
        ]
        self.entry_type_combo.addItems(self.entry_types)
        form_layout.addRow(QLabel("Entry Type:"), self.entry_type_combo)

        self.jurisdiction_combo = QComboBox()
        self.jurisdictions = ["Lex Aequies", "Lex Postalis", "Lex Naturalis", "Civil", "Ecclesiastical", "N/A"]
        self.jurisdiction_combo.addItems(self.jurisdictions)
        if default_jurisdiction in self.jurisdictions:
            self.jurisdiction_combo.setCurrentText(default_jurisdiction)
        form_layout.addRow(QLabel("Jurisdiction Tag:"), self.jurisdiction_combo)

        self.notes_edit = QTextEdit()
        self.notes_edit.setPlaceholderText("Enter detailed notes for this entry.")
        form_layout.addRow(QLabel("Notes:"), self.notes_edit)

        # Associated Clause IDs - simple text input for now, comma-separated
        self.clause_ids_edit = QLineEdit()
        self.clause_ids_edit.setPlaceholderText("Optional: e.g., CL-123, CL-456")
        form_layout.addRow(QLabel("Associated Clause IDs (CSV):"), self.clause_ids_edit)

        # Status - default to Active
        self.status_combo = QComboBox()
        self.statuses = ["Active", "Archived", "Under Review", "Completed"]
        self.status_combo.addItems(self.statuses)
        self.status_combo.setCurrentText("Active")
        form_layout.addRow(QLabel("Status:"), self.status_combo)


        main_layout.addLayout(form_layout)

        self.button_box = QDialogButtonBox(QDialogButtonBox.StandardButton.Ok | QDialogButtonBox.StandardButton.Cancel)
        self.button_box.accepted.connect(self.accept_entry)
        self.button_box.rejected.connect(self.reject)
        main_layout.addWidget(self.button_box)

        self.setMinimumWidth(450)
        self.setMinimumHeight(350)

    def accept_entry(self):
        title = self.title_edit.text().strip()
        if not title:
            QMessageBox.warning(self, "Input Error", "Title cannot be empty.")
            return # Keep dialog open

        self.entry_data = {
            "title": title,
            "entry_type": self.entry_type_combo.currentText(),
            "jurisdiction_tag": self.jurisdiction_combo.currentText(),
            "notes": self.notes_edit.toPlainText().strip(),
            "associated_clause_ids": [cid.strip() for cid in self.clause_ids_edit.text().split(',') if cid.strip()],
            "status": self.status_combo.currentText()
            # Timestamp and entry_id will be auto-generated by LedgerEntry model
        }
        super().accept() # Close dialog with QDialog.Accepted result

    def get_entry_data(self) -> dict:
        return self.entry_data

if __name__ == '__main__':
    from PyQt6.QtWidgets import QApplication
    import sys
    app = QApplication(sys.argv)
    dialog = AddLedgerEntryDialog()
    if dialog.exec():
        print("Entry Data:", dialog.get_entry_data())
    else:
        print("Dialog cancelled.")
    sys.exit(app.exec())
